//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class event2Entities : DbContext
{
    public event2Entities()
        : base("name=event2Entities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<@event> events { get; set; }
    public virtual DbSet<image> images { get; set; }
    public virtual DbSet<user> users { get; set; }
    public virtual DbSet<reservation> reservations { get; set; }
    public virtual DbSet<eventType> eventTypes { get; set; }
}
